##### 1.Sayılardan oluşan bir boyutlu array oluşturun. Arrayi oluştururken sayıların veri tipini integer olarak belirtelim.

Oluşturulan arrayin boyut, eleman sayısı bilgilerine bakalım.

In [7]:
!pip install numpy
import numpy as np
arr1=np.array([1,2,3,4,5],dtype="int")
arr2=np.array([[1,2,3],[4,5,6]])
print("arr1'in boyutu:",arr1.ndim)
print("arr2'nin boyutu:",arr2.ndim)
print("arr1'in eleman sayısı:",arr1.size)
print("arr1'nin eleman sayısı:",arr2.size)


Defaulting to user installation because normal site-packages is not writeable
arr1'in boyutu: 1
arr2'nin boyutu: 2
arr1'in eleman sayısı: 5
arr1'nin eleman sayısı: 6


##### 2. Aşağıda verilen iki boyutlu ve üç boyutlu arrayi oluşturalım. Bu arraylerin boyut, eleman sayısı, satır, sütun bilgilerine ulaşalım. 

İki boyutlu array:
[[1,2,6,7],
 [4,3,9,5]]

Üç boyutlu array:
[[[7,5,14],[21,8,11]],
 [[8,6,20],[14,3,9]]]

 

In [9]:
arr2=np.array([[1,2,6,7],[4,3,9,5]])
arr3=np.array([[[7,5,14],[21,8,11]],[[8,6,20],[14,3,9]]])
print("arr2'nin buyutu:",arr2.ndim)
print("arr2'nin eleman sayısı:",arr2.size)
print("arr2'nin satır ve sütun bilgisi:",arr2.shape)
print("-------------")
print("arr3'nin buyutu:",arr3.ndim)
print("arr3'nin eleman sayısı:",arr3.size)
print("arr3'nin satır ve sütun bilgisi:",arr3.shape)


arr2'nin buyutu: 2
arr2'nin eleman sayısı: 8
arr2'nin satır ve sütun bilgisi: (2, 4)
-------------
arr3'nin buyutu: 3
arr3'nin eleman sayısı: 12
arr3'nin satır ve sütun bilgisi: (2, 2, 3)


##### 3. İstenilen elamanlara ulaşmak için arrayler üzerinde indexleme işlemi yapalım

In [10]:
#İki boyutlu arraydaki 2 elemanına ulaşalım
arr2=np.array([[1,2,6,7],[4,3,9,5]])
arr2[0,1]

2

In [11]:
#İki boyutlu arraydaki 7 elemanına ulaşalım
arr2=np.array([[1,2,6,7],[4,3,9,5]])
arr2[0,3]


7

In [12]:
#Üç boyutlu arraydaki 9 elemanına ulaşalım
arr3=np.array([[[7,5,14],[21,8,11]],[[8,6,20],[14,3,9]]])
arr3[1,1,2]

9

In [13]:
#Üç boyutlu arraydaki 5 elemanına ulaşalım
arr3=np.array([[[7,5,14],[21,8,11]],[[8,6,20],[14,3,9]]])
arr3[0,0,1]

5

##### 4. Arrayler üzerinde slicing işlemi uygulayalım.

In [14]:
#İki boyutlu arraydaki 2,6 elemanlarına ulaşalım
arr2=np.array([[1,2,6,7],[4,3,9,5]])
arr2[0,1:3]


array([2, 6])

In [15]:
#İki boyutlu arraydaki 3,9,5 elemanlarına ulaşalım
arr2=np.array([[1,2,6,7],[4,3,9,5]])
arr2[1,1:]


array([3, 9, 5])

In [16]:
#Üç boyutlu arraydaki 21,8,11 elemanlarına ulaşalım
arr3=np.array([[[7,5,14],[21,8,11]],[[8,6,20],[14,3,9]]])
arr3[0,1,:]

array([21,  8, 11])

In [17]:
#Üç boyutlu arraydaki 6,20 elemanlarına ulaşalım
arr3=np.array([[[7,5,14],[21,8,11]],[[8,6,20],[14,3,9]]])
arr3[1,0,1:]


array([ 6, 20])

##### 5. 5 satır 3 sütunluk sıfırlardan ve birlerden oluşan iki tane iki boyutlu array oluşturalım. Bu arrayleri satır ve sütun bazında birleştirelim.

In [22]:
import numpy as np
arr1=np.zeros((5,3),dtype="int")
arr2=np.ones((5,3),dtype="int")
print("arr1:",arr1)
print("arr2:",arr2)
satir_birlestirme=np.concatenate((arr1,arr2),axis=0)
print("satır bazında birleştirme:")
print(satir_birlestirme)
sutun_birlestirme=np.concatenate((arr1,arr2),axis=1)
print("sütun bazında birleştirme:")
print(sutun_birlestirme)


arr1: [[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
arr2: [[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
satır bazında birleştirme:
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
sütun bazında birleştirme:
[[0 0 0 1 1 1]
 [0 0 0 1 1 1]
 [0 0 0 1 1 1]
 [0 0 0 1 1 1]
 [0 0 0 1 1 1]]
